### ISSUE TITLE
Implement a way for a recipe to define an `immutable` context value

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#104]
Some recipes hardcode a context value that is required by a query. For example, the `try_efficiency` recipe hardcodes the `branches` context to `try`.

However, since the query it uses has a `branches` eval in it, this context gets added to the cli/webapp even though modifying it has no affect. We should figure out a way for recipes to signal that a query-based context value is going to be hardcoded.

**Comment by TrangEmily** [comment]
Hi @ahal I think we can close this issue.

**Comment by ahal** [comment]
Yes, thanks!
