### ISSUE TITLE
Cron failures

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/active-data-recipes#105]
Looking at 

    c:\python36\Scripts\adr.exe config_durations --verbose

the `branches` is empty 

At this point in the debugger https://github.com/mozilla/active-data-recipes/blob/master/adr/recipes/config_durations.py#L15 `branches is, indeed, empty

![image](https://user-images.githubusercontent.com/2334429/51579667-d0939400-1e8f-11e9-9283-0d2235f15bee.png)

**Comment by klahnakoski** [comment]
I blame the lack of default value from this changeset:

https://github.com/mozilla/active-data-recipes/commit/57eddf8921a0f23f1893b5bcf3c653120f51091d#diff-1fd0892d2b93fe30e321b96b4a4e9e4aL14

**Comment by ahal** [comment]
This got fixed and hasn't been failing recently. Thanks for the investigation!
