### ISSUE TITLE
Ability to open a query in ActiveData's query tool

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#17]
Sometimes it's nice to run a query in ActiveData's actual query tool (http://activedata.allizom.org/tools/query.html). It's possible to POST a query to that endpoint and receive a URL back. Maybe we could create an `adr-query --debug <query>` which instead of running the query, get's the URL from the web interface and opens it in the user's browser.

I'm not sold on the name `--debug`, open to other ideas.

**Comment by sashafierce** [comment]
Hello @ahal! I am an Outreachy aspirant and I feel I like this project the most thus far hence I would like to start towards solving something, I have installed the `adr` module and tried to use it( although I'm getting errors with some commands, not sure if its expected behavior). 
I think I understand this issue, please let me know if this is good bug to start with. Thanks :smile:

**Comment by ahal** [comment]
Hi @sashafierce , thanks for your interest! Yes you are more than welcome to try this out :). And yes, it's expected that some of the recipes won't work. ActiveData is undergoing a bit of migration so things aren't as stable as we'd like. But as long as you see data from some of the recipes that's good enough for our purposes (the `adr inspect` one is nice and simple to test out).

This is a little more complicated than some of the other ones, but depending on your experience level it shouldn't be too hard. In a nutshell, you'll need to add a an extra parameter to the POST request we send to ActiveData (`save=True`). Then in the JSON response, you'll find a `meta.saved_as` key. You can append this to the query tool's URL and then open it in a browser with the `webbrowser` standard library. You'll need to add some sort of `cli` flag to hook this up.

Feel free to reach out if you have any questions

**Comment by sashafierce** [comment]
Thanks @ahal  I am looking into this, if someone else wants to try they are welcome to!

**Comment by emily1511** [comment]
Hi @ahal and @sashafierce. I followed above suggestion and found that the POST request is `{"from":"meta.tables","meta":{"save":true}}`. Can I try this one? Thanks.

**Comment by klahnakoski** [comment]
@TrangEmily you must include the query you want opened.  In your example the query is `{"from":"meta.tables"}`, which is a special metadata query, and make me wonder why you chose that table.

**Comment by klahnakoski** [comment]
@TrangEmily the sequence will look something like

1. The command line options will dictate a particular recipe/query to send to ActiveData
2. Your code will intercept that send and attach `{"meta":{"save":true}}` to the query
3. Your code will intercept the response and record the `{"meta":{"saved_as":UID}}`
4. Your code returns the response to the recipe/query, and let it do its work.
5. Your code will also open http://activedata.allizom.org/query#query_id=UID in the browser
