### ISSUE TITLE
Combine recipe and query runner into one

### ISSUE THREAD

**Issue by worldomonation** [mozilla/active-data-recipes#19]
The current default when user runs `adr` in the CLI invokes the recipes parser, which then begins looking for a recipe of the name provided e.g. `adr unittest_skip_count`.

While this is handy if the default use case is recipes, it is unintuitive if the user intends to run a query. The user must run `adr-query ...` and if the user does not have tab completion or is new to the tool it can be confusing.

Proposal:

- combine `adr-query` and `adr` to one CLI call
- default to running recipes if no action is specified

**Comment by ahal** [comment]
+1

I'd propose:

```
$ adr recipe <recipe>
$ adr query <query>
$ adr <name>
```

The last case could just search for <name> in the recipes and possibly even the queries if none were found. We can use argparse's subparsers feature to implement this.

**Comment by worldomonation** [comment]
Issue has been addressed by https://github.com/mozilla/active-data-recipes/pull/29.
