### ISSUE TITLE
Create a recipe to track skipped/disabled tests

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#27]
There used to be a tool called `test-informant` that would report how many tests we have skipped and under which directories. But it went unmaintained and no longer works. We should create a recipe to replace it.

**Comment by anshultale** [comment]
hi @ahal , I would like to work on this.

**Comment by ahal** [comment]
Hi @anshultale, this one might not be the greatest one to get started on to be honest. It requires quite a bit of inside knowledge of how the data is stored and what it means. I'll spend a bit of time this afternoon to file some new issues that would be more suitable. Thanks for your interest though!

**Comment by anshultale** [comment]
Thanks @ahal, can you please point me to one of the suitable issues whenever you add them.

**Comment by ahal** [comment]
@anshultale will do! I filed a few but they get taken pretty quickly :). I'll try to find some more to file today.

**Comment by TrangEmily** [comment]
Hi @ahal, where can I get the old version of `test-informant`, or any information about the raw query which will be called in this recipe & post-processing requirement. Thank you.

**Comment by MadinaB** [comment]
I am trying to resolve this issue and have made some small recipe which is related to this issue. I made it very simple in order to check if I am moving in correct directions. Could you please check this? If everything is correct, I plan to add extra arguments for it.

**Comment by ahal** [comment]
Thanks for your contribution!

**Comment by ahal** [comment]
Fixed by https://github.com/mozilla/active-data-recipes/commit/dc2cd4c32ec84e53c4cb21301c06d483b92df1dd
