### ISSUE TITLE
Create a configuration object

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#30]
There are certain pieces of data (e.g ActiveData endpoint, log, verbose, etc) that need to be passed around from module to module. Currently they are handled sort of ad-hoc (often by manipulating globals). It would be cleaner to have a configuration object we could store information on. We could ultimately pass this into the recipes (and therefore we could also store arbitrary metadata they might need).

We might eventually also want a configuration file, but I don't think this is worth implementing just yet.

**Comment by TrangEmily** [comment]
Hi @ahal I want to try this one. Follow your suggestion, I intend to do like this:
1. Make a configuration class that read from config file
2. User can overwrite any parameter using command line arguments (i.e --url)
3. Other modules can get data of this class.

**Comment by ahal** [comment]
Thanks, sounds like a good plan!

I don't have a super clear idea how this should be implemented, but I think you're on the right track. So Iet's see how the PR looks and we can iterate on it if necessary.

**Comment by ahal** [comment]
Thanks for your contribution!
