### ISSUE TITLE
try_usage is busted on new cluster

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/active-data-recipes#32]
The try_usage recipe does not work using the new cluster. The data it needs is there, but `{"select":"changeset.description"}` is returning `null`.

```
{
	"from":"repo",
	"select":["push.user","changeset"],
	"where":{"and":[
		{"eq":{"branch.name":"try"}},
		{"gte":{"push.date":{"date":"today-week"}}}
	]},
	"sort":{"push.user":"desc"},
	"limit":10
}
```

The `repo` is not storing the description separate from the whole document.  I will look into this

**Comment by ahal** [comment]
This will hopefully just be fixed in upstream ActiveData and no action will be necessary here. But I'll leave it open to help keep track of it.

**Comment by ahal** [comment]
This got fixed upstream, thanks Kyle!
