### ISSUE TITLE
Raise `MissingDataError` in query.py if ActiveData doesn't return any data

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#41]
Previously we modified the `try_usage.py` recipe to raise MissingDataError if it detected that ActiveData returned empty results.

We should move this directly into query.py so that it'll happen for all of the queries regardless. This check should happen in the `query_activedata` function, just before the json data is returned.

**Comment by Pokinawa** [comment]
I am gonna have a look at this now

**Comment by ahal** [comment]
Thanks for your contribution!
