### ISSUE TITLE
`adr task_durations --branch <branch>` doesn't work

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#45]
Add a `print(query_args)` statement here:
https://github.com/mozilla/active-data-recipes/blob/master/adr/recipes/task_durations.py#L34

Then run `adr task_durations --branch mozilla-inbound`. Notice that the 'branch' value is still the default set instead of just ['mozilla-inbound'].

**Comment by kerlynNkep** [comment]
Hi @ahal, am here and will look into this right away.

**Comment by ahal** [comment]
Thanks! Let me know if you have any questions.

**Comment by kerlynNkep** [comment]
Hi @ahal, I have something working out like this


![issue45](https://user-images.githubusercontent.com/19359585/47067054-f7329680-d1df-11e8-99d0-bb1b9726541d.png)

I also wish to verify if the branches listed in DEFAULT_BRANCHES are all the branches that exist at the moment.

**Comment by ahal** [comment]
Looks great, thanks! Feel free to put up a PR and I'll take a look. There are more branches outside of `DEFAULT_BRANCHES`, but you shouldn't need to worry about that here.

**Comment by kerlynNkep** [comment]
@ahal okay sending a PR straight away.

**Comment by kerlynNkep** [comment]
Hi @ahal  i have sent a PR. Please can you check and get back to me. And also please would want you to assign me to another task while you are reviewing this.

**Comment by ahal** [comment]
Thanks for the fix @kerlynNkep! Looks like all the issues got taken in the meantime, but I'll try to file some more today or tomorrow. I'll mention you in it when I do.
