### ISSUE TITLE
Improve web app design

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#48]
In issue #34 we landed a basic flask web frontend to run the recipes. It is currently very bare bones (just a list of links with no styling). We should try to improve the look and feel of this.

I have almost no webdev experience, so I won't be able to provide much guidance. My intuition is that a framework like React might be overkill for this purpose, and just using a style library like bootstrap would probably be good enough. But I can be convinced otherwise!

Some ideas to get the ball rolling:

* A visually defined area for the results
* Select recipe from a drop down next to  a single `Run` button
* A banner along the top for things like a title / more information / etc

I'm not a designer, so happy to defer to what others think would be best.

**Comment by ahal** [comment]
Hi @mesumbejoan, in issue #34 you expressed some interest in improving the design of the web-app. Now that it's landed is this still something you would want to work on? Let me know!

**Comment by ahal** [comment]
Wanted to note that to fix this issue, we should stick to modifying the templates and css. There shouldn't be any need to touch the backend (python) side of the app.

Also this issue will likely have a lot of conflicts with issue #49. So if both are being worked on at the same time, we can expect conflicts. This is fine, just be aware that there may be the need to rebase from time to time.

**Comment by mesumbejoan** [comment]
@ahal Yes, I would still like to work on this. If that is Ok by you, please let me know.

**Comment by terrameijar** [comment]
Hello.

I am interested in working on this, but I haven't figured out how to run the flask app. Could someone point me in the right direction?

**Comment by ahal** [comment]
Hi @terrameihar, you can run the following:

    $ cd app
    $ flask run

Then open the printed link in your browser. Hope that helps!

**Comment by mesumbejoan** [comment]
@ahal I have made a pull request on this. Please could you have a look?
Here it is: #59

**Comment by terrameijar** [comment]
@ahal Thanks for the help in getting me setup. I also just submitted a PR :) 
https://github.com/mozilla/active-data-recipes/pull/60

**Comment by ahal** [comment]
Thanks to both of you! Apologies for the overlap contribution overlap here, I'll take both contributions into account regardless of whether or not the PR ends up getting merged.

**Comment by rabyatouyimga** [comment]
@ahal Thanks. Please is there any other issue which you would recommend for me ? I am applying to this project for Outreachy, and I would like to have more tasks to understand the code base even more.

**Comment by ahal** [comment]
I had a chance to pull both PRs down and test them out, they both look really nice! Thanks for the hard work.

I just wanted to note that I'm going to hold off merging either PR until after the internship has been decided. I'd like whoever gets picked to have some control over the direction of the web-app so having both options to use as a potential starting point will be very helpful! Thanks again and hope you understand.

**Comment by mesumbejoan** [comment]
@ahal. Thank you for testing this. I would have loved to do a PR on some of the python code, but time is against us. Thanks for communicating this with us; I wish you the best as you pick who will work on this. Thank you,

**Comment by ahal** [comment]
@mesumbejoan no matter the results of this selection, if you are looking for Python experience and are interested in contributing further to Mozilla, I would be more than happy to help you find some bugs to work on in our main code base (this module is just a tiny fraction of the Python we run here at Mozilla). Though the barrier to entry is a bit higher than this project (we don't use Github or support vanilla git). The offer is open to anyone else reading this as well.

**Comment by MadinaB** [comment]
@ahal I am in. This is my first time committing to Mozilla and I can feel it being addictive :D

**Comment by ahal** [comment]
https://github.com/mozilla/active-data-recipes/commit/ff995681e37804f1b48aed07576bffff9e6df0e4
