### ISSUE TITLE
Running `adr <recipe> -- --help` no longer displays recipe help

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#55]
This is a regression from a cli refactoring. I'm not exactly sure what's happening, but I think it's because we dynamically add the subparsers in based on the arguments:
https://github.com/mozilla/active-data-recipes/blob/master/adr/cli.py#L173

I believe fixing this issue will involve making it so the subparsers are always added regardless of whether or not 'recipe' or 'query' show up in the args.

We should try to preserve the current behaviour however where we can run all of:

1. `adr <recipe>`
2. `adr recipe <recipe>`
3. `adr query <query>`

**Comment by kerlynNkep** [comment]
Hi @ahal. Ill get on this.

**Comment by kerlynNkep** [comment]
Hi @ahal, please i wish to find out from you which among these frameworks [Angular, Flask and React]  will be used in designing the dashboard for this project.

**Comment by ahal** [comment]
Hi @kerlynNkep, this specific issue isn't related to the web dashboard, so doesn't require any frameworks to complete. It requires python only in the `cli.py` file. If you wish to do some webdev, you can try your hand at issue #48. Just be aware that some other applicants may also be working on it, so there's a chance I won't be able to merge your work if you do.

This issue will require some in-depth knowledge of python's `argparse` module.

**Comment by kerlynNkep** [comment]
@ahal  Yes i know that its not related to web dashboard. The question was relating to the internship project. Am sorry posting the question here even though its not related to the issue.

**Comment by MadinaB** [comment]
Hello!

I think this [fix](https://github.com/mozilla/active-data-recipes/pull/63) deals with the bug, could you please check it up?
