### ISSUE TITLE
Stop supporting python 2

### ISSUE THREAD

**Issue by ahal** [mozilla/active-data-recipes#58]
There isn't really a good reason this needs to support both python 2 and python 3. To simplify things, let's just support 3 only. Steps to take:

1. Remove the py2 call from tox.ini
2. Remove `six` from the dependencies in setup.py
3. Remove all references to `six` in the code (and replace them with their python 3 equivalents).

**Comment by kerlynNkep** [comment]
@ahal  thanks for referring me to this issues. I will also work on this as well.

**Comment by terrameijar** [comment]
@ahal I would like to work on this if its still up for grabs or any other issues that you can point me to.

**Comment by kerlynNkep** [comment]
Hi @terrameijar am on it already.

**Comment by rabyatouyimga** [comment]
@ahal @kerlynNkep ok, since you are working on this, I shall look for another issue for my first contribution.
@ahal please is there any task you suggest I work on?

**Comment by kerlynNkep** [comment]
Hello @ahal i have sent a PR. Please can you check it and get back to me

**Comment by ahal** [comment]
Thanks for your contribution @kerlynNkep!

**Comment by ahal** [comment]
@rabyatouyimga I apologize, but the final application deadline is tomorrow and at this point it's too late to start recording contributions. There should be several projects that have requested additional applications and have extended their deadline. I'd recommend trying to find one of those to contributions.

But thanks for your interest!
